sf2films_user_mycontent:
    pattern:  /mycontent/{page}
    defaults: { _controller: Sf2filmsUserBundle:Default:showMyContent, page: 1 }
    requirements:
        page:  \d+

sf2films_user_mycontent_add:
    pattern:  /mycontent/add
    defaults: { _controller: Sf2filmsUserBundle:Default:addMyContent }
    methods:  [POST]

sf2films_user_mycontent_del:
    pattern:  /mycontent/del
    defaults: { _controller: Sf2filmsUserBundle:Default:delMyContent }
    methods:  [POST]

facebook_security_check:
    pattern: /facebook/check

facebook_security_logout:
    pattern: /facebook/logout

fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"