security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, my_fos_facebook_provider]
        fos_userbundle:
            id: fos_user.user_provider.username
        my_fos_facebook_provider:
            id: my.facebook.user

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            fos_facebook:
                app_url: "http://apps.facebook.com/sf2films/"
                server_url: "http://sf2films.local/facebookApp/"
                login_path: /facebook/login
                check_path: /facebook/check
                default_target_path: /
                provider: my_fos_facebook_provider
            logout:       true
            anonymous:    true
            logout:
                invalidate_session: false

#TODO finish this code
    acl:
        connection: default

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/(films|genre|person)/add$, role: ROLE_ADMIN }
        - { path: ^/(films|genre|person)/(edit|delete)/\d+$, role: ROLE_ADMIN }

        - { path: ^/facebook/, role: [ROLE_FACEBOOK] }
        - { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] } # This is the route secured with fos_facebook