sf2films_comment_add:
    pattern:  /comment/add/{id}
    defaults: { _controller: Sf2filmsCommentBundle:Comment:addElement }

sf2films_comment_edit:
    pattern:  /comment/edit/{id}
    defaults: { _controller: Sf2filmsCommentBundle:Comment:editElement }

sf2films_comment_del:
    pattern:  /comment/del
    defaults: { _controller: Sf2filmsCommentBundle:Comment:delElement }
    methods:  [POST]
