parameters:
#    sf2films_comment.example.class: Sf2films\CommentBundle\Example

services:
#    sf2films_comment.example:
#        class: %sf2films_comment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
