sf2films_homepage:
    pattern:  /
    defaults: { _controller: Sf2filmsFilmsBundle:Default:index}

sf2films_films_all:
    pattern:  /films/{page}
    defaults: { _controller: Sf2filmsFilmsBundle:Films:showAll, page: 1 }
    requirements:
        page:  \d+

sf2films_films_add:
    pattern:  /films/add
    defaults: { _controller: Sf2filmsFilmsBundle:Films:addElement }

sf2films_films_del:
    pattern:  /films/del/{id}
    defaults: { _controller: Sf2filmsFilmsBundle:Films:delElement }

sf2films_films_element:
    pattern:  /films/{translit}
    defaults: { _controller: Sf2filmsFilmsBundle:Films:showElement }

sf2films_films_by_genre:
    pattern:  /films/genre/{translit}
    defaults: { _controller: Sf2filmsFilmsBundle:Films:showAllByGenre }

sf2films_films_by_person:
    pattern:  /films/person/{translit}
    defaults: { _controller: Sf2filmsFilmsBundle:Films:showAllByPerson }


sf2films_films_genre:
    pattern:  /genre
    defaults: { _controller: Sf2filmsFilmsBundle:Genre:showAll }

sf2films_films_genre_add:
    pattern:  /genre/add
    defaults: { _controller: Sf2filmsFilmsBundle:Genre:addElement }

sf2films_films_genre_del:
    pattern:  /genre/del/{id}
    defaults: { _controller: Sf2filmsFilmsBundle:Genre:delElement }



sf2films_films_person:
    pattern:  /person
    defaults: { _controller: Sf2filmsFilmsBundle:Person:showAll }

sf2films_films_person_add:
    pattern:  /person/add
    defaults: { _controller: Sf2filmsFilmsBundle:Person:addElement }

sf2films_films_person_del:
    pattern:  /person/del/{id}
    defaults: { _controller: Sf2filmsFilmsBundle:Person:delElement }