sf2films_homepage:
    pattern:  /{_locale}
    defaults: { _controller: Sf2filmsFilmsBundle:Default:index, _locale: ru }
    requirements:
        _locale: en|ru

sf2films_films_all:
    pattern:  /{_locale}/films/{page}
    defaults: { _controller: Sf2filmsFilmsBundle:Content:showAll, page: 1, _locale: ru }
    requirements:
        page:  \d+
        _locale: en|ru

sf2films_films_add:
    pattern:  /{_locale}/films/add
    defaults: { _controller: Sf2filmsFilmsBundle:Content:addElement, _locale: ru }
    requirements:
        _locale: en|ru

sf2films_films_edit:
    pattern:  /{_locale}/films/edit/{id}
    defaults: { _controller: Sf2filmsFilmsBundle:Content:editElement, _locale: ru }
    requirements:
        _locale: en|ru

sf2films_films_del:
    pattern:  /films/del/{id}
    defaults: { _controller: Sf2filmsFilmsBundle:Content:delElement }

sf2films_films_element:
    pattern:  /{_locale}/films/{slug}
    defaults: { _controller: Sf2filmsFilmsBundle:Content:showElement, _locale: ru }
    requirements:
        _locale: en|ru

sf2films_films_by_genre:
    pattern:  /{_locale}/films/genre/{translit}/{page}
    defaults: { _controller: Sf2filmsFilmsBundle:Content:showAllByGenre, page: 1, _locale: ru }
    requirements:
        page:  \d+
        _locale: en|ru

sf2films_films_by_person:
    pattern:  /{_locale}/films/person/{translit}
    defaults: { _controller: Sf2filmsFilmsBundle:Content:showAllByPerson, _locale: ru }
    requirements:
        _locale: en|ru

sf2films_sitemap:
    pattern:  /{_locale}/sitemap
    defaults: { _controller: Sf2filmsFilmsBundle:Content:showSiteMap, _format: xml, _locale: en}
    requirements:
        _format:  xml
        _locale: en|ru



sf2films_films_genre:
    pattern:  /{_locale}/genre
    defaults: { _controller: Sf2filmsFilmsBundle:Genre:showAll, _locale: ru }
    requirements:
        _locale: en|ru

sf2films_films_genre_add:
    pattern:  /{_locale}/genre/add
    defaults: { _controller: Sf2filmsFilmsBundle:Genre:addElement, _locale: ru }
    requirements:
        _locale: en|ru

sf2films_films_genre_edit:
    pattern:  /{_locale}/genre/edit/{id}
    defaults: { _controller: Sf2filmsFilmsBundle:Genre:editElement, _locale: ru }
    requirements:
        _locale: en|ru

sf2films_films_genre_del:
    pattern:  /{_locale}/genre/del/{id}
    defaults: { _controller: Sf2filmsFilmsBundle:Genre:delElement }



sf2films_films_person:
    pattern:  /{_locale}/person
    defaults: { _controller: Sf2filmsFilmsBundle:Person:showAll, _locale: ru }
    requirements:
        _locale: en|ru

sf2films_films_person_add:
    pattern:  /{_locale}/person/add
    defaults: { _controller: Sf2filmsFilmsBundle:Person:addElement, _locale: ru }
    requirements:
        _locale: en|ru

sf2films_films_person_edit:
    pattern:  /{_locale}/person/edit/{id}
    defaults: { _controller: Sf2filmsFilmsBundle:Person:editElement, _locale: ru }
    requirements:
        _locale: en|ru

sf2films_films_person_del:
    pattern:  /person/del/{id}
    defaults: { _controller: Sf2filmsFilmsBundle:Person:delElement }